### ISSUE TITLE
"Waiting for privacy badger"

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerchrome#449] opened 2015-06-26 01:01 UTC
When I loaded the latest github version of PB for Chrome, I started getting a lot of browser status notices (bottom left corner) saying "waiting for privacy badger".  They *imply* that the browser is being way slower because of PB.  We should figure out if that's really the case, and if so what we can do about it...

**Comment by cooperq** [comment] 2015-06-26 01:51
That is what happens whenever we are blocking (e.g. when we are in the function called during the 'beforeSendHeaders' event. It is not a sign of breakage, but we should make sure that our blocking calls are as optimized as possible.

**Comment by SwartzCr** [comment] 2015-06-26 22:52
I wonder if this has anything to do with sites that have single points of failure for blocked resources, for example if they have <script> tags that have their endpoint blocked and the site refuses to load beyond that

**Comment by cooperq** [comment] 2015-07-15 19:02
also related to #319

**Comment by johnblommers** [comment] 2016-01-14 00:22
Today, Chrome was spending so much time waiting for privacy badger that I had to disable it. The **real delays** it creates have become intolerable. The following site triggered my action:

http://blog.nanowrimo.org/post/137225942166/i-published-my-nano-novel-4-things-i-learned-from

**Comment by jebrennan** [comment] 2016-01-21 06:26
Today, 1/20/16, I disabled Privacy Badger (2015.12.3) in Chrome Version 47.0.2526.111 (64-bit) because the delays were interminable. Minutes would go by. Hope it gets fixed.

**Comment by stuaxo** [comment] 2016-03-01 13:04
Seem to spend most of my time looking at "Waiting for privacy badger" ... would be good if there was a way of finding out what is actually happening during that time.

**Comment by anand-bhat** [comment] 2016-03-03 23:00
https://www.cloudflare.com/http2/ also appears to trigger this. JavaScript CPU profile of the extension background page when the page is being loaded:

![image](https://cloud.githubusercontent.com/assets/7332442/13512542/4c546d06-e169-11e5-81e8-0ba4c6ed17c4.png)

**Comment by QJeffR** [comment] 2016-03-08 15:58
Had to disable Privacy Badger on Chrome Version 49.0.2623.75 (64-bit) this morning. I was seeing "Waiting for Privacy Badger" message on every tab where I took an action, including existing tabs (YouTube, Medium) and new tabs (Google search). 

I've also seen a number of cases recently where all Chrome tabs fail to load, with the message "resolving host" -- I'm afraid these may also be due to Privacy Badger. Let me know if I can provide any further information to track these down.

**Comment by benjaminpwarren** [comment] 2016-03-10 04:43
I was also just now having an issue trying to follow links, "Waiting for Privacy Badger". All tabs were affected.

I just did a "chrome://restart" and I'm no longer having a problem.

Just in case it's somehow relevant, I'm connected via a VPN service (the above mention of cloudfare made me think it is somehow relevant, seeing as I'm seeing their "suspicious activity" / "I'm not a robot" pages a lot recently whilst connected via VPN service).

**Comment by kevwil** [comment] 2016-03-11 23:08
I'm also having this issue, where multiple tabs hang with "waiting for extension Privacy Badger" for quite a few minutes with no end in sight. I'm giving up, I've had to disable it. :( Hope it get fixed soon.

**Comment by bitops** [comment] 2016-03-15 20:06
I just had the same issue and to remove Privacy Badger from Chrome. It's not acceptable to cause a 5 to 15 second wait time.

**Comment by tulensrma** [comment] 2016-03-17 12:05
I have this issue as well. OSX 10.11.3, Chrome v 49.0.2623.87 (64-bit). Restarting Chrome fixes the issue temporarily until it appears again.

**Comment by ThomkDC** [comment] 2016-03-20 00:16
I just gave up and removed Privacy Badger. No matter what I tried I could not get past "waiting for extension privacy badger." I could not open any webpage under any circumstance. I will try again when I see that this issue is taken seriously, and resolved.

**Comment by Levino** [comment] 2016-03-22 16:06
Same here.

**Comment by JBildstein** [comment] 2016-03-24 22:25
I'm having the same issue, chromium 49.0.2623.87 on Debian 8.3
It happens randomly but if it happens, it's on all tabs that are loading.
Workaround -> go to extensions, disable PB and re-enable again (can be done right away).

**Comment by QuentinMoss** [comment] 2016-03-26 13:18
Having the same issue as JBildstein. Disable and re-enable is the only fix I've found.

Chrome: Version 49.0.2623.87 (64-bit)
OS X 10.10.5

**Comment by 4kbt** [comment] 2016-03-26 16:10
Just hit this, too. Disable/re-enable fixed it. 

Chromium 49.0.2623.87 , Debian build, x86 box.

**Comment by Seth-Johnson** [comment] 2016-04-03 14:53
I am also experiencing this issue. "waiting for privacy badger" is adding ~10-15 seconds to page load time. Neither `chrome://restart` nor re-enabling the extension solved the issue. it'll have to stay disabled on my machine for now.

**Comment by safiire** [comment] 2016-04-05 17:11
This happens to me at least once per day, where I need to disable and then re-enable Privacy badger.

Chrome Version 49.0.2623.110 (64-bit)
OSX 10.9.5

**Comment by Chaz6** [comment] 2016-04-09 13:19
I have this issue with Chrome 49.0.2623.112 m (64-bit) on Windows 10.

**Comment by paulb** [comment] 2016-04-13 07:26
I've just removed Privacy Badger as this is happening more frequently, and it's not just a few seconds wait. Pages will not load until the extension is disabled and reenabled. Includes loading of pages on the local network which have no tracking ability that I know of, e.g., my router admin page.

Chrome Version 49.0.2623.110 (64-bit)
OS X 10.9.5

**Comment by berlincount** [comment] 2016-04-13 13:03
Chrome Version 49.0.2623.112 m (64-bit)

Windows 8.1

**Comment by cooperq** [comment] 2016-04-13 18:45
okay I think I have finally tracked this down and have a fix for this in #807
I will be pushing out a new release today which should fix this problem.

**Comment by bitops** [comment] 2016-04-13 19:09
Thank you for the fix.

**Comment by XtinaSchelin** [comment] 2016-04-18 11:07
It's still happening as of today. Not sure if this was intended to be a full fix or a "well, it happens _less_" fix. Swift disable/re-enable of the extension gets me over the hurdle.

**Comment by cooperq** [comment] 2016-04-19 01:54
@XtinaSchelin can you confirm that you have the latest version? 
Everyone else on this thread: has my fix worked for you or are you still having this problem?

If you are still having this problem please take the following steps: 
1. open chrome://extensions/
2. click the checkbox to enable developer mode
3. click the link under privacy badger that says "inspect background page" 
4. in the popup click "profiles" and then "collect javascript cpu profile" and then "start"
5. navigate to a page that is giving you the problem
6. once the page has loaded click "stop"
7. Save the profile that you created which is listed under cpu profiles, and attach it here.

**Comment by cooperq** [comment] 2016-04-19 01:55
The fixed version is 2016.4.13 please make sure you are on that version.

**Comment by yoniLavi** [comment] 2016-04-19 15:11
I'm on 2016.4.13 and just had it happen to me again. I don't see an "inspect background page", so I couldn't troubleshoot it.

**Comment by frosforever** [comment] 2016-04-21 14:51
Still having the issue sporadically. Reloading chrome or the extension seems to work.
Version:  2016.4.13
Chrome: Version 50.0.2661.75 (64-bit)
OS: OSx 10.10.5

**Comment by cooperq** [comment] 2016-04-22 17:24
okay, I will keep looking into this. Though I suspect that my time is better spent on removing the ABP machinery which should solve this and a bunch of other bugs and make privacy badger way faster.

**Comment by stuaxo** [comment] 2016-04-23 19:44
If it will simplify looking into many bugs, including this, then the removing that machinery could make sense?  - (Having said that, this bug has been the impetus for me to switch back to ff and a different extension, so maybe not the best person to listen to).

**Comment by anand-bhat** [comment] 2016-04-28 06:31
While my [earlier comment](https://github.com/EFForg/privacybadgerchrome/issues/449#issuecomment-192007697) was for a page that was loading albeit slowly due to Privacy Badger, I ran into the issue where the page is stuck at "Waiting for Privacy badger" for eternity with no activity. I enabled Javascript CPU profiling per @cooperq's [instructions](https://github.com/EFForg/privacybadgerchrome/issues/449#issuecomment-211683157) but I observed that the background page inspection page was behaving erratically. After I stopped CPU profiling, it continued to record. The profile did not load and the Start/ Stop button was disabled or non-functional. All other tabs on the background inspection page (Elements, Console, etc.) were not working as well.

Disabling the extension and re-enabling it fixed the problem. Are there any other things that can be captured if/ when this occurs again?

**Comment by vball525** [comment] 2016-05-05 01:58
happened twice today. Privacy Badger version 2016.04.13, Mac OSX 10.11.4, Chrome Version 50.0.2661.94 (64-bit). i previously reported this in another bug that was closed as a duplicate. this is a new instance of the issue.

**Comment by pandorra2** [comment] 2016-05-15 22:15
got the same bug several times over the last ~3 months. last time a couple of minutes before i posted this.

**Comment by cooperq** [comment] 2016-05-17 05:36
Okay, This should be completely fixed in the latest version of privacy badger. As of today I have only deployed it to 10% of users (it has some huge changes!) but if you want to try it out early you can take the following steps. 
1. Download the crx file [from the chrome web store] (https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP1rX98iOE5SwxVXgdVTMTKqobiCFyOuS_jNFoVMdRhW-bEA7QhvVJw2hrKrZS8b8ThMYsv0t-wxxLr4D-Sm2ZC1AMZSmuW2zjq5MsW529CVI2Rtq2QO7xWEQg/pkehgijcmpdhfbdbbnkijodmdjhbjlgp_main.crx)
2. Open a new tab to [chrome://extensions](chrome://extensions)
3. Drag the downloaded file and drop it onto the extensions window. 
You should now have Privacy Badger version 2016.5.15
If this doesn't fix the problem please let me know. If you find any new bugs please file a separate issue.

**Comment by dieseltravis** [comment] 2016-05-17 13:23
I just updated my Chromebook to 2016.5.16
![screenshot 2016-05-17 at 9 17 08 am](https://cloud.githubusercontent.com/assets/17863/15323584/ae24ccc4-1c10-11e6-8b2d-9e2e5c43b73e.png)

The CPU for the extension never drops below 30% (it is 55% in that image) and browsing is impossible.

**Comment by cooperq** [comment] 2016-05-17 18:12
Great! the options page does still admittedly have some kinks to work out, but I think that it will be improving a lot in the next couple of weeks. Let me know if you have any more high cpu usage or 'waiting for privacy badger' issues.

**Comment by pandorra2** [comment] 2016-05-18 18:04
kk, will keep my eye on it. thanks man!

btw pls fix year 2015 in changelog ;)
https://github.com/EFForg/privacybadgerchrome/blob/master/doc/Changelog

**Comment by cooperq** [comment] 2016-05-18 18:27
I'm going to assume this is fixed for now unless someone tells me otherwise.

**Closed by cooperq** 2016-05-18 18:27 UTC
Labels: bug, High priority

**Comment by stuaxo** [comment] 2016-05-18 19:30
Awesome, will be trying in next few days,thanks for the work :)

**Comment by vball525** [comment] 2016-05-24 18:15
please open back up. just happened again to me. disabled. version 2016.5.23. chrome. mac.

**Comment by frosforever** [comment] 2016-05-31 22:30
Just hit this again.
Version:  2016.5.24
Chrome: Version 50.0.2661.102 (64-bit)
OS: OSx 10.11.5

**Comment by cooperq** [comment] 2016-06-02 21:26
@frosforever @vball525 if you are able to consistently reproduce this please open a new issue with steps to repro.
