### ISSUE TITLE
PB sometimes blocks third parties that are owned by the first party site

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#689] opened 2015-11-16 15:55 UTC
Sometimes PB will block CDNs or other third party content owned by the first party site
For a long time we felt that there was no solution for this, since PB works in a 'dumb' way wrt to blocking things.
According to Francois disconnect exposes a list of what third parties are owned by various first parties. If this list is small enough I suggest we include it with PB (to be updated semi-regularly, or regularly from an EFF mirror) and use it to not block first party owned sites.
This would require a small change to the blocking code, but should be an easy check against a hash map.

**Comment by cooperq** [comment] 2015-11-18 00:28
:+1: I think that this is a good idea as well, we could have a more fuzzy notion of first partyness and treat these owned domains as first parties to the top level domain. We just need to get this list from disconnect.

**Comment by michael-oneill** [comment] 2015-11-18 07:41
The DNT Tracking Status Resource has a “same-party” property, an array of strings representing domains, which lets top level browsing contexts (“first-party” sites) declare domains that are managed by the same data-controller (the entity responsible for the “first-party”).

 

This is better than relying on a curated list. It is also another encouragement for sites to respect DNT.

 

Mike

**Comment by cooperq** [comment] 2015-11-23 20:38
Is there any formation on how wide spread adoption of the same-party property is? I haven't been able to find any sites that use it.

**Comment by michael-oneill** [comment] 2015-11-23 22:41
There are a couple http://www.w3.org/wiki/Privacy/TPWG/TPE_Implementation_Report but there is as yet little reason to support it. As more UAs implement the full rec. hopefully more sites will support it. There are nor many sites including the EFF DNT policy yet either.

**Comment by cooperq** [comment] 2016-05-17 07:00
Duplicate of #first party

**Closed by cooperq** 2016-05-17 07:00 UTC
Labels: enhancement, Good Volunteer Task
