### ISSUE TITLE
New Feature: Online backup of rules and settings

### ISSUE THREAD

**Issue by lordraiden** [EFForg/privacybadgerchrome#745] opened 2016-02-11 09:54 UTC
Could you add a feature to store in google drive / chrome the settings and rules of PB? more or less like ublock origin does 
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings       (see backup)

We won't lose our lists of blocks that we have been "farming" for months if we change pc, or we lose the data of the browser for whatever reason...

Ideally you could capture all this data and centralize it in order to provide better block lists by default or learn better how to make a better behavior blocking rules.

It will allow you as well to mitigate issues like this:
https://github.com/EFForg/privacybadgerchrome/issues/353

**Comment by cooperq** [comment] 2016-02-17 20:20
duplicate of #121

**Closed by cooperq** 2016-02-17 20:20 UTC
Labels: duplicate
