### ISSUE TITLE
privacy badger deactivated but still replaces elements with icon

### ISSUE THREAD

**Issue by nekromoff** [EFForg/privacybadgerchrome#586] opened 2015-08-25 13:22 UTC
i.e. "privacy badger has replaced this twitter button"
but it is deactivated, page has been reloaded

**Comment by SwartzCr** [comment] 2015-08-25 14:21
It sounds like the deactivate code likely just stops the blocking onBeforeRequest actions, but not the other code of privacy badger such as social widgets. Since there's a enable/disable social widget replacing in the options page this should be an easy fix to add it to the deactivate, I'll look into that right now

**Comment by SwartzCr** [comment] 2015-08-25 14:56
from src/webrequest.js
727   } else if (request.checkReplaceButton) {                                       
728     if (Utils.isPrivacyBadgerEnabled(tabHost) && Utils.isSocialWidgetReplacementEnabled()) {

Which means that it won't replace the button unless privacy badger is enabled for that site. I just tested and couldn't reproduce the issue. My guess is that your browser is caching the loaded page somehow, try hard refresh? (ctrl+shift+r)
I'm going to close this but if you're getting it consistantly and can take a screenshot of it (and maybe check for errors in the browser console) then feel free to re-open it

**Comment by nekromoff** [comment] 2015-08-25 15:00
OK, steps to reproduce:
PB is enabled.
1. go to http://careermaker.sk/ako-dokaze-mala-firma-ziskat-dobreho-programatora/
2. Disable PB.
3. Reload page using F5 or whatever.
4. social buttons are still covered by PB icon (quite ugly, BTW)
![2](https://cloud.githubusercontent.com/assets/8550349/9470125/c89d6c60-4b4a-11e5-9c73-eebfa28d4678.png)

**Comment by nekromoff** [comment] 2015-08-25 15:01
BTW, maybe unrelated - but I don't think PB is disabled as clicking on it shows "Loading..." indefinitely.
![3](https://cloud.githubusercontent.com/assets/8550349/9470156/f8d884b4-4b4a-11e5-8211-227ca41e9e46.png)

**Comment by cooperq** [comment] 2015-08-27 18:34
Can you tell me which version of privacy badger you are running?

**Comment by nekromoff** [comment] 2015-08-27 18:52
1.0.2

**Comment by SwartzCr** [comment] 2015-09-24 17:45
@nekromoff out of curiosity which browser are you running? This is the repository for the chrome version of Privacy Badger, but your version number seems to indicate that you're using the Firefox version

**Comment by nekromoff** [comment] 2015-09-24 20:13
That's correct, I am sorry, I didn't know this was chrome only.

**Comment by cooperq** [comment] 2015-10-02 16:05
It is, please repost in the firefox issue queue EFForg/privacybadgerfirefox

**Closed by cooperq** 2015-10-02 16:05 UTC
