### ISSUE TITLE
"waiting for privacy badger" running in google chrome in perpetuity

### ISSUE THREAD

**Issue by Dowwie** [EFForg/privacybadgerchrome#825] opened 2016-05-02 10:45 UTC
on  May 2nd, at about 6:30am EST , I could no longer access any web sites as "waiting for privacy badger" blocked google chrome's requests

**Comment by cooperq** [comment] 2016-05-02 19:39
duplicate of #449

**Closed by cooperq** 2016-05-02 19:39 UTC
Labels: duplicate
