### ISSUE TITLE
PrivacyBadger is missing blocking of HTML5 cookieless tracking

### ISSUE THREAD

**Issue by charlesprogrammr** [EFForg/privacybadgerchrome#587] opened 2015-08-25 18:37 UTC
With HTML5 came a *new attribute to allow tracking of which links on a page are followed*, which means we don't even have to click them. The attribute in question is called the ***'ping' attribute***, and I don't see anything anywhere that addresses its abilities. PrivacyBadger should strip these attributes from each and every page to stop the use before its use becomes widespread.

**Comment by michael-oneill** [comment] 2015-08-25 21:14
A very good point. Here is a description of it http://www.w3schools.com/TAGs/att_a_ping.asp

**Comment by cooperq** [comment] 2015-08-27 18:33
Seems worth doing, I doubt this would even break anything we care about.

**Comment by charlesprogrammr** [comment] 2015-09-19 01:04
Thanks, Michael. Thanks, Cooper.

**Comment by gunesacar** [comment] 2016-09-21 20:58
I checked how ping requests appear in `onBeforeRequest` listeners and found that tabID and the frameID of the ping requests are set to -1.

So PB can't know which tab and frame the pings belong to and thinks that they come from an _internal tab_ since they satisfy the `tabId < 0` condition in [`_isTabChromeInternal`](https://github.com/EFForg/privacybadgerchrome/blob/master/src/webrequest.js#L525).

Ping requests have `details.type = ping`, so it's easy to distinguish them from other requests. PB could block all pings to tracking domains, but I can't think of a way to exclude pings of tabs that PB is disabled on.

Following Chrome bugs should be the root cause:
https://crbug.com/522124
https://crbug.com/522129

Not sure, what to do about that.

**Comment by cooperq** [comment] 2016-09-22 19:09
Hmm interesting. Another option would be to block all ping requests. @gunesacar @michael-oneill how much do you think this would break stuff?

**Comment by michael-oneill** [comment] 2016-09-23 17:47
I doubt if it would break anything the user would care about, though it might stop some data going to the collectors. This is another situation where per-site user consent would work. If DNT header is not 0 in the beacon request, block it.

**Comment by gunesacar** [comment] 2016-09-25 13:22
Here are some use cases I ran into:
- https://crbug.com/611453 (first comment)
- https://github.com/gorhill/uBlock/issues/1493#issuecomment-223293992

Yet, I agree with @michael-oneill; blocking pings shouldn't break any critical functionality.

**Comment by gunesacar** [comment] 2016-09-25 13:47
This _block-all-the-pings_ approach only needs to be there until the Chrome bugs are fixed (then we'll know which tab/frame/origin is the initiator).

The good news is, one of the Chrome bugs is already fixed and landed in the dev channel. Motivated me to send a PR, but feel free to ignore if you think we better wait or not happy with the following behavior:

1. PB will block all pings sent by open tabs until [#522124](https://crbug.com/522124) is landed (already landed in Chrome dev)
2. PB will block all pings sent on `onunload` events until [#522129](https://crbug.com/522129) is landed
3. Once the fixes are landed, PB will treat pings as any other request

**Closed** 2016-10-06 02:19 UTC
Labels: enhancement, Good Volunteer Task
