### ISSUE TITLE
Privacy Badger relies on Ad Block Plus

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#629] opened 2015-10-08 18:24 UTC
Currently Privacy Badger includes a version of Ad Block Plus that it uses to manage it's filter settings. This is an artifact of the first iteration of Privacy Badger where we thought we might include outside blocklists. We have now thoroughly eschewed the use of block lists, yet still are relying on an increasingly out of date version of the Ad Block Plus code. 

The Ad Block Plus code does two main things. It defines the data structure that Privacy Badger stores its blocking data in (frequencyHeuristic, userRed, userYellow, userGreen). Additionally we use its built in functions to search these data structures when determining how to treat a given third party. This code is very complex and very out of date, making it hard to change functionality.

These functions can be re-implemented in a simpler way making it easier to maintain them, and hopefully increasing the speed of thes operations and privacy Badger as a whole.

This issue will track the progress of this change. I'll be closing ABP related issues and moving then to this thread, where they can be tracked along with the move away from ABP.

**Comment by cowlicks** [comment] 2015-11-07 20:23
FYI this is a duplicate of #119 some of the discussion there is probably relevant.

**Closed** 2016-05-17 07:01 UTC
Labels: enhancement, Good Volunteer Task, High priority
