### ISSUE TITLE
High CPU usage in chrome on certain pages

### ISSUE THREAD

**Issue by RCNunya** [EFForg/privacybadgerchrome#618] opened 2015-10-02 02:43 UTC
I have found that when I have Privacy Badger turned on, when I visit Enjin websites, (Clan based forums and websites) the page formating changes to make it very difficult to read and the CPU usage for Privacy Badger goes up in chrome and causes my CPU fan to wind up.

Here is a video on one such pages formatting issues and CPU use before and after activating Privacy Badger.
First is normal view of the page, then I activate Privacy Badger and reload the page, you can see the formatting of the page change and the Chrome CPU usage increased because of Privacy Badger use.

http://screencast.com/t/a6kdLh15

**Comment by SwartzCr** [comment] 2015-10-08 18:25
unfortunately I don't have flash so i can't watch the video. If you could link to the related domain that would help. Additionally I might consider closing this issue in favor of #629

**Comment by RCNunya** [comment] 2015-10-08 18:29
The two I know I had issues on were:
http://www.misfitregiment.com/
and
http://www.unitedallies.net/forum

On Thu, Oct 8, 2015 at 1:25 PM, Noah Swartz <notifications@github.com>
wrote:

> unfortunately I don't have flash so i can't watch the video. If you could
> link to the related domain that would help. Additionally I might consider
> closing this issue in favor of #629
> <https://github.com/EFForg/privacybadgerchrome/issues/629>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/privacybadgerchrome/issues/618#issuecomment-146645466>
> .
>



--

**Comment by remexre** [comment] 2016-03-31 01:16
I'm having really high CPU usage and not-loading with Chrome on [BitBucket](https://bitbucket.org), unless I kill the Chrome process for Privacy Badger.

**Comment by cooperq** [comment] 2016-04-07 01:13
I think this is a duplicate of #324

**Closed by cooperq** 2016-04-07 01:13 UTC
