### ISSUE TITLE
Tumblr Profile Links

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [EFForg/privacybadgerchrome#721] opened 2015-12-31 21:59 UTC
On Tumblr if you visit your own profile and click on (for example) an image to delete it or edit it the buttons at the top right are replaced with "Join Tumblr" even if you are signed in. This also applies to when you haven't selected an image but are on your profile and want to edit it. The edit button is also replaced.

**Comment by KUPOinyourWINDOW** [comment] 2015-12-31 22:01
I came back to add that I saw this issue a few weeks back and have just tried to replicate it and it seems to be fixed. You may want to check if there has already been a patch for this or not.

**Comment by cooperq** [comment] 2016-02-05 21:39
I am also unable to reproduce this now. Closing for now, please re-open and comment if it happens again.

**Comment by KUPOinyourWINDOW** [comment] 2016-02-09 05:38
I'm running into the issue again but have no more information I can add. It's happening the same as before, screenshots can be sent if desired.

**Comment by cooperq** [comment] 2016-02-09 21:44
Can you determine which domains are being blocked by privacy badger?

**Comment by KUPOinyourWINDOW** [comment] 2016-02-09 22:14
I've just gone to check for you and the issue isn't happening (again). It's worth mentioning that this morning I did re-install Kubuntu, my OS of choice.
This appears to be an on and off thing and as I'm not very technical (I just love the extension) I can't offer any useful information, sorry.

**Comment by cooperq** [comment] 2016-02-17 20:28
Closing for now until we have more information

**Closed** 2016-02-17 20:28 UTC
