### ISSUE TITLE
Google Drive download failure

### ISSUE THREAD

**Issue by cwolsen** [EFForg/privacybadgerchrome#893] opened 2016-08-10 14:18 UTC
When trying to download files from Google Drive with Privacy Badger enabled downloads fail. Message is merely "Failed - Network error." Disabling extension for Google Drive corrects the problem, but, previous to last week, it worked just fine.

**Comment by cooperq** [comment] 2016-08-11 01:46
Duplicate of #534 , working on a fix in #781

**Closed by cooperq** 2016-08-11 01:46 UTC
