### ISSUE TITLE
First run tab opens every startup

### ISSUE THREAD

**Issue by adairjim** [EFForg/privacybadgerchrome#544] opened 2015-08-10 16:25 UTC
Is anyone else experiencing this behavior? Installed Privacy Badge on Chrome 44.0.2403.130 and now every start of Chrome will reopen the first run tab for Privacy Badger. I've tried uninstalling the extension and reinstalling and it remains.

**Comment by SwartzCr** [comment] 2015-08-10 16:58
have you tried clicking through the comic? Try that and then let me know if this persists

**Comment by adairjim** [comment] 2015-08-10 17:02
Yes, went through 16 slides to the end, closed down Chrome, then reopened and still got the tab.

**Comment by cooperq** [comment] 2015-11-07 00:36
I am unable to reproduce this, can anyone else reproduce this? @adairjim are you still having this problem?

**Comment by mrjagsr** [comment] 2016-03-30 20:21
I am also having the same issue, every time I start Chrome.
The first run page always appears.
I tried all of the same steps adairjim did.
Chrome Version 49.0.2623.110 m

**Comment by cooperq** [comment] 2016-03-31 07:02
So it has been mentioned that CC-cleaner might cause this behavior, are any of you running cc cleaner by any chance?

**Comment by mrjagsr** [comment] 2016-03-31 12:41
CC-cleaner was the problem, thanks.
Will Privacy Badger eventually be able to run with CC-cleaner running in the background?

**Comment by cooperq** [comment] 2016-04-02 00:53
I hope so! I will have to look into this further.

**Comment by temp-999** [comment] 2016-04-02 01:35
Windows 10 Pro 64 bit, latest update, installed mid-Jan 2016
Chrome 49.0.2623.110 m (64-bit), latest update
Privacy Badger extension 2016.3.2, latest update
CCleaner v5.16.5551 (64-bit), latest update

Same problem as OP but mine started the last week or so of March 2016.

cooperq's guidance is much appreciated.

Started Chrome up and then exited. Started CCleaner up and ran the Cleaner. Restarted Chrome and the Privacy Badger tab appeared. Exited Chrome. In CCleaner, Cleaner, Applications, Google Chrome all entries were checked. Unchecked some entries, ran Cleaner and then retried Chrome. Eventually narrowed it down to Internet Cache. Next, did Analyze before running Cleaner and double clicked on Google Chrome - Internet Cache. Started Excluding files (right click file(s) and select Add to Exclude list (excluded files show up in Options, Exclude). Re-ran testing cycle. After some time, narrowed it down to multiple files. Decided that I'd had enough and Excluded folder C:\Users\<your name>\AppData\Local\Google\Chrome\User Data\Profile 1\File System\. This is currently working for me.

**Comment by cooperq** [comment] 2016-04-07 00:36
ah excellent, I suspect that this might actually be fixed by #775

**Comment by cooperq** [comment] 2016-05-17 06:18
Okay, This should be completely fixed in the latest version of privacy badger. As of today I have only deployed it to 10% of users (it has some huge changes!) but if you want to try it out early you can take the following steps. 
1. Download the crx file [from the chrome web store] (https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP1rX98iOE5SwxVXgdVTMTKqobiCFyOuS_jNFoVMdRhW-bEA7QhvVJw2hrKrZS8b8ThMYsv0t-wxxLr4D-Sm2ZC1AMZSmuW2zjq5MsW529CVI2Rtq2QO7xWEQg/pkehgijcmpdhfbdbbnkijodmdjhbjlgp_main.crx)
2. Open a new tab to [chrome://extensions](chrome://extensions)
3. Drag the downloaded file and drop it onto the extensions window. 
You should now have Privacy Badger version 2016.5.15
If this doesn't fix the problem please let me know. If you find any new bugs please file a separate issue.

**Closed by cooperq** 2016-05-17 06:18 UTC
Labels: bug, Good Volunteer Task
