### ISSUE TITLE
"Referer" header modification conflict with Referer Control extension

### ISSUE THREAD

**Issue by roycewilliams** [EFForg/privacybadgerchrome#582] opened 2015-08-21 05:08 UTC
Under Chrome 40.0.2214.115 unknown (64-bit), the Referer Control extension, version 0.59, is currently throwing this warning:

This extension failed to modify the request header "Referer" of a network request because the modification conflicted with another extension (Privacy Badger).

Is this a known issue or class of issues with Privacy Badger, is there a workaround, or is this something that needs to be addressed by the Referer Control team?

**Comment by cooperq** [comment] 2015-08-24 23:29
duplicate of #562.  We strip the referer header for sites that are cookieblocked to increase privacy. Chrome only lets one extension modify a given header. I would say this works as designed for both addons.

**Closed by cooperq** 2015-08-24 23:29 UTC
