### ISSUE TITLE
CCleaner breaks Privacy Badger in Opera & Chrome

### ISSUE THREAD

**Issue by bkrcrc** [EFForg/privacybadgerchrome#803] opened 2016-04-07 09:04 UTC
1- Add privacy badger to your fresh Opera browser. (drag&drop chrome .crx to Opera)
2- Make some custom settings and rules on Privacy Badger settings
3- Close browser, run CCleaner and make a cleaning
4- Open Opera browser again you will see the "Welcome" message of Privacy Badger just like first install
5- Badger thinks it is just installed and all your settings&configurations are gone!

Please report it to Piriform(CCleaner) and make a fix for yourself.

Thanks

**Comment by cooperq** [comment] 2016-05-17 06:57
Duplicate of #803

**Closed by cooperq** 2016-05-17 06:57 UTC
