### ISSUE TITLE
PB loads tutorial with chrome.

### ISSUE THREAD

**Issue by ozhuntsman** [EFForg/privacybadgerchrome#806] opened 2016-04-09 03:05 UTC
Every time I load my chrome browser, Privacy Badger automatically loads it's tutorial. 

The link I keep getting is:

chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/skin/firstRun.html

I reported this problem weeks ago to the eff,org link, but no help so far ??!!
I can't find a link to STOP this behaviour ! 
If I don't receive help soon, I'll stop using Privacy Badger.

I might add, as a retired IT Eng, I find your bug reporting system is tortuous and time consuming. 
I have no intention of ever using Github for programming. The procedure to report a bug with Github is laborious and time consuming.

**Comment by bkrcrc** [comment] 2016-04-09 08:43
This is because CCleaner or WiseDisk Cleaner. These cleaner deleted your preferences in Chrome & Opera browser. Firefox does not effected. Please take a look at this issue report.
#803

**Comment by ozhuntsman** [comment] 2016-04-09 09:07
OK Thanks. I do use Ccleaner.
What setting does CCleaner delete?
I looked them over, but nothing is obvious.
I am a retired IT engineer. If I know what to look for I'll fix it.
I support several sites (PC users) who are pensioners and they all use
Ccleaner.
..Keith




On 9 April 2016 at 18:43, Bekir <notifications@github.com> wrote:

> This is because CCleaner or WiseDisk Cleaner. These cleaner deleted your
> preferences in Chrome & Opera browser. Firefox does not effected. Please
> take a look at this issue report.
> #803 <https://github.com/EFForg/privacybadgerchrome/issues/803>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/privacybadgerchrome/issues/806#issuecomment-207747793>
>



-- 


*                          "Freedom is the right to tell people what they
do not want to hear." - George Orwell *

*Don't let governments or politicians take your privacy or freedom away
from you. They will once they are elected !*

**Comment by bkrcrc** [comment] 2016-04-09 11:32
1 - Open CCleaner > click Options > Exclude
2 - Click Add > File > Browse
3 - Navigate to: C:\Users\%USER%\AppData\Local\Google\Chrome\User Data\Default\Local Storage\
4 - Click on the Privacy Badger's localstorage file (for Opera this is it "chrome-extension_pkehgijcmpdhfbdbbnkijodmdjhbjlgp_0.localstorage-journal" > click Open > OK.

**Comment by ozhuntsman** [comment] 2016-04-09 13:40
Thanks for the info, however Exclude doesn't stop it.
This is the CCleaner Chrome entry I excluded..


*C:\Users\Keith\AppData\Local\Google\Chrome\User Data\Default\Local
Storage\chrome-extension_pkehgijcmpdhfbdbbnkijodmdjhbjlgp_0.localstorage*

*There's also a journal entry (0 bytes) for the same item, but excluding it
also, didn't stop it. I don't use Opera btw.*
*I've attached a PrtSc of the file entry.*
*I closed & reopened both Chrome and CCleaner after adding the Exclude, but
the Privacy Badger tutorial (first run) still runs. *
*Is there a registry entry for it ?*
*Have I missed something ?*

*..Keith*



On 9 April 2016 at 21:32, Bekir <notifications@github.com> wrote:

> 1 - Open CCleaner > click Options > Exclude
> 2 - Click Add > File > Browse
> 3 - Navigate to: C:\Users\%USER%\AppData\Local\Google\Chrome\User
> Data\Default\Local Storage\
> 4 - Click on the Privacy Badger's localstorage file (for Opera this is it
> "chrome-extension_pkehgijcmpdhfbdbbnkijodmdjhbjlgp_0.localstorage-journal"
> > click Open > OK.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/privacybadgerchrome/issues/806#issuecomment-207773824>
>



-- 


*                          "Freedom is the right to tell people what they
do not want to hear." - George Orwell *

*Don't let governments or politicians take your privacy or freedom away
from you. They will once they are elected !*

**Comment by bkrcrc** [comment] 2016-04-09 16:56
Hi Keith,

I have no answers fro your questions, sorry. As I said I am also faced this problem but we got no reply. I am still trying to solve the temporary problem.

**Comment by ozhuntsman** [comment] 2016-04-09 18:18
OK, I'm a Pro CCleaner user, so I'll have a shot at the CCleaner support
guys to see if they have the answer. I'll let you know what if anything
they supply..maybe an update to CCleaner ?
..Keith

On 10 April 2016 at 02:57, Bekir <notifications@github.com> wrote:

> Hi Keith,
>
> I have no answers fro your questions, sorry. As I said I am also faced
> this problem but we got no reply. I am still trying to solve the temporary
> problem.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/privacybadgerchrome/issues/806#issuecomment-207817784>
>



-- 


*                          "Freedom is the right to tell people what they
do not want to hear." - George Orwell *

*Don't let governments or politicians take your privacy or freedom away
from you. They will once they are elected !*

**Comment by bkrcrc** [comment] 2016-04-09 18:47
It will be much appreciated Keith.
The problem is CCleaner side, the CCleaner also have some problems with Adguard adblocker extension. Adguard has the same problem, as well.

Thank you.

**Comment by redranamber** [comment] 2016-04-10 11:28
I found a solution to this by making an exception for the folder "\AppData\Roaming\Opera Software\Opera Stable\File System\000" I don't have Chrome to check but it likely follows a similar path.

**Comment by bkrcrc** [comment] 2016-04-11 14:13
Hi,
For temporary solution. On CCleaner at "Applications" tab disable the "Internet Cache" option.
From now on, CCleaner won't interfere with Privacy Badger.
Screenshot: https://i.imgur.com/uaIvQ97.png

**Comment by ozhuntsman** [comment] 2016-04-11 16:07
Hi Bekir,
CCleaner tech support are working to correct the problem in a coming
release.  The CCleaner tech support suggestion which I've copied below,
included a suggested fix for AdGuard as well...  Your solution to stop
clearing the Chrome Internet Cache succeeded.
Thanks.

..Keith

You should be able to use the Exclude rules to prevent this from happening
by following these instructions:

   - Open CCleaner > click Options > Exclude
   - Click Add > File > Browse
   - Navigate to: C:\Users\%USER%\AppData\Local\Google\Chrome\User
   Data\Default\Local Storage\
   - Click on the "https_adguard.com_0.localstorage-journal" file > click
   Open > OK.

Similarly, excluding the files "chrome-extension_
pkehgijcmpdhfbdbbnkijodmdjhbjlgp_0.localstorage-journal" or
"chrome-extension_hdokiejnpimakedhajhdlcegeplioahd_0.localstorage-journal"
may keep PrivacyBadger's settings from being erased.


On 12 April 2016 at 00:13, Bekir <notifications@github.com> wrote:

> Hi,
> For temporary solution. On CCleaner at "Applications" tab disable the
> "Internet Cache" option.
> From now on, CCleaner won't interfere with Privacy Badger.
> Screenshot: https://i.imgur.com/uaIvQ97.png
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/privacybadgerchrome/issues/806#issuecomment-208367336>
>



-- 


*                          "Freedom is the right to tell people what they
do not want to hear." - George Orwell *

*Don't let governments or politicians take your privacy or freedom away
from you. They will once they are elected !*

**Comment by cooperq** [comment] 2016-04-12 02:02
Duplicate of #803

**Closed** 2016-05-17 06:57 UTC
Labels: duplicate
