### ISSUE TITLE
players.brightcove.net breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#818] opened 2016-04-27 21:31 UTC
http://www.express.co.uk/news/weird/664891/Mystery-mushroom-cloud-filmed-billowing-from-Area-51-alien-base-Clinton-has-eyes-on

players.brightcove.net needs to be moved to yellow (or surrogate'd) in order to fix the video.

**Comment by terrorist96** [comment] 2016-04-28 03:12
More examples:
http://www.dyson.co.uk/haircare/supersonic
http://www.dyson.com/haircare/supersonic.aspx

**Comment by terrorist96** [comment] 2016-04-29 20:57
http://www.mirror.co.uk/news/world-news/isis-hackers-release-hit-list-7864663

**Comment by yieldman** [comment] 2016-04-30 10:38
Privacy Badger does not detect any tracking cookies on players.brightcove.net so it isn't blocking the connection on my testing environment. This problem may be unique to you.
(Tested with turning prevalenceThreshold = 1, If we cant reproduce with that, we probably never will. )

**Comment by terrorist96** [comment] 2016-04-30 15:49
Looks like it's fixed for me too now.

**Comment by terrorist96** [comment] 2016-05-02 20:28
@cooperq actually this is still broken for me on a different chrome profile.

**Comment by yieldman** [comment] 2016-05-03 05:43
I am not sure if this an appropriate response but i would suggest you to reinstall privacy badger or reproduce this issue with a fresh profile since #824 #823 and this issue cannot be reproduced except on your machine. Custom blacklist should not be an issue with this one since i tested this by turning prevalenceThreshold variable to 1 and PB still doesn't block any domains your setup seem to have problem with. 
for eg:-
 #823 cdns.gigya.com delivers 1 script with no tracking cookies hence PB doesn't block it in the first place which is the expected behavior . (detected through umatrix.)
If anything changes with a fresh copy please post here.

**Comment by terrorist96** [comment] 2016-05-03 06:07
Uninstalling PB would result in losing the years of browsing I've done with it. As we both know, PB only works better the longer you use it. If I change the value for an item, it displays the arrow icon on the right, indicating that this is a custom value and clicking the icon would reset it to the default value. That icon isn't present for any of the items, except for disqus, which I have chosen to whitelist myself.
I'm not sure what the Threshold variable thing you're talking about is and how to change it.

**Comment by terrorist96** [comment] 2016-05-03 06:13
For example, the #823 issue is present on my main chrome profile, but using a test profile that I don't use for normal browsing, the cdns.gigya isn't being blocked. So the only reason I can think that my main profile blocks it is because it has more experience and knows that gigya is a tracker while my test profile hasn't recognized that yet.

**Comment by yieldman** [comment] 2016-05-03 06:33
[Variable reference](https://github.com/EFForg/privacybadgerchrome/blob/master/src/heuristicblocking.js#L47).
> As we both know, PB only works better the longer you use it.

Not necessarily . This variable tells PB to add a domain to its blocklist only if its tracking cookies are detected on atleast 3 seperate domains. Switch it to one and PB wont wait to find it on other occasions. Helpful for testing issues.
> Using a test profile that I don't use for normal browsing, the cdns.gigya isn't being blocked. So the only reason I can think that my main profile blocks it is because it has more experience and knows that gigya is a tracker while my test profile hasn't recognized that yet.

This probably means that cdns.gigya used to serve tracking cookies on multiple domains which PB recognised and blocked. But it doesnt anymore and PB isnt aware of the improvement. 

If you wish to verify if cdns.gigya is serving you tracking cookies, all you need to do is :- 
1. clear all cookies.
2. temporarily disable privacy badger for http://www.recipe.com/
3. visit http://www.recipe.com/
4. Go to chrome://settings/content , click on all cookies and site data , and see it any cookie has been registered on cdns.gigya domain name.

To save you trouble, i check on my setup and it isnt setting any cookies.

**Comment by terrorist96** [comment] 2016-05-03 15:16
> This probably means that cdns.gigya used to serve tracking cookies on multiple domains which PB recognised and blocked. But it doesnt anymore and PB isnt aware of the improvement.

So then this is a usability issue. Privacy Badger should recognize instances like this and automatically update the blocking status of the item. The average user isn't going to go through the trouble of figuring this stuff out. What do you think @cooperq

**Comment by cooperq** [comment] 2016-05-03 16:54
Sure, but we also look at what cookies the browser is sending. If the user never clears their cookies then it will keep sending them to a site even once the site stops using them. And this will look like tracking to privacy badger. 
I agree with your suggestion in principal but I'm at a loss for how to implement it.

**Comment by yieldman** [comment] 2016-05-03 18:28
Theoritical solution of this problem would be that PB periodically adds domains from its blacklist to a temperory whitelist, lets it set cookies , then check the entropy of that cookie to determine if it still leaves tracking cookies and if it still does, add it back to the blacklist. But adding such a feature would add unnecessary complexity to the PB and not to mention how exhausting it would be to implement , maintain and debug this feature.

**Comment by terrorist96** [comment] 2016-05-12 01:06
Another example:
http://www.independent.co.uk/news/world/americas/burgers-contain-rat-and-human-dna-study-finds-a7023661.html

players.brightcove.com breaks the video for me.

**Comment by terrorist96** [comment] 2016-05-13 18:07
So now player.brightcove.net defaults to green for me on my main profile, but is still red on my test profile. I have cleared all brightcove cookies on the test profile as well.

**Comment by terrorist96** [comment] 2016-05-17 00:12
http://www.mirror.co.uk/news/world-news/businessman-raising-1m-recreate-911-7981317

**Comment by cooperq** [comment] 2016-05-17 06:00
The issue is probably fixed then. You should be able to move players.brightcove.com to green on your main profile .

**Comment by terrorist96** [comment] 2016-05-19 04:13
And this is still broken for me on my test profile (which also received the May 16 update). Clearing cookies doesn't help.

**Comment by cooperq** [comment] 2016-05-19 22:53
I mean, it is fixed by brightcove and will be fixed for people that haven't already blocked it. Those that have blocked it will have to manually unblock it.

**Closed by cooperq** 2016-05-19 22:53 UTC
Labels: Site-bug

**Comment by terrorist96** [comment] 2016-05-20 00:08
But I never explicitly blocked it. PB saw it fit to block it by itself, and has yet to decide to unblock it. I'm just basing this on how an average user would use PB. They won't fiddle with the different settings.

**Comment by terrorist96** [comment] 2016-05-20 00:08
But I never explicitly blocked it. PB saw it fit to block it by itself, and
has yet to decide to unblock it. I'm just basing this on how an average
user would use PB. They won't fiddle with the different settings.

**Comment by terrorist96** [comment] 2016-06-21 01:20
@cooperq I don't know what to tell you man, but on some of my Chrome profiles, PB still chooses to block brightcove player by default. Look at the screenshot. There's no arrow on the right hand side to click to reset it to the default setting. This **is** the default setting.
![capture](https://cloud.githubusercontent.com/assets/12802056/16215073/aaa6ecbc-372c-11e6-80e2-85caebb30a48.PNG)

**Comment by cooperq** [comment] 2016-06-29 00:55
are those  profiles using the current version of privacy badger?

**Comment by terrorist96** [comment] 2016-06-29 02:12
Yes - 2016.5.24

**Comment by cooperq** [comment] 2016-06-29 17:55
Sorry I think you misunderstood me. The problem is fixed for people who haven't had players.brightcove.net blocked by privacy badger yet, because brightcove is no longer using cookies. If your badger has already heuristically blocked brightcove it won't get unblocked magically, privacy does not re-check things after it has blocked them. 
However, I can add players.brightcove.net to the cookieblock list so that it will move to yellow for everyone.

**Comment by terrorist96** [comment] 2016-06-29 17:57
That would work. Thanks!
