### ISSUE TITLE
Pages take a long time to load with Privacy Badger on my Mac.

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#477] opened 2015-07-19 13:43 UTC
"Long time" can be up to a minute.

While a page is loading, there is sporadic lots of CPU activity, and I cannot do anything else in Chrome, such as copy text from another page.  

Then, when pages have finished loading, there is delayed response to scrolling up/down, sometimes for several seconds.

The load time seems to get worse the more Chrome windows/tabs I have open.  So of course the workaround is to use fewer windows, but using only one or two windows (which seems to behave OK) is kind of cramping.

Right now I have three Chrome windows open, one of which has two tabs, and this setup exhibits the issue.
http://petapixel.com/
http://www.thedailybeast.com/
http://digg.com (the other tab in this window is qz.com, with Privacy Badger disabled)

Chrome: Version 43.0.2357.134 (64-bit)
Privacy Badger: Version: 2015.4.1, Updated: April 1, 2015

Mac OS X 10.6.8 (10K549)

  Model Identifier:	iMac11,3
  Processor Name:	Intel Core i5
  Processor Speed:	2.8 GHz
  Number Of Processors:	1
  Total Number Of Cores:	4
  L2 Cache (per core):	256 KB
  L3 Cache:	8 MB
  Memory:	12 GB

Cable ISP download speed: ~30Mbps, upload: ~4.25Mbps

----
NOTE:
This is *not a problem* with Chrome on my HP 64-bit 16MB Windows 7 computer at the office.  I've been running Privacy Badger there for months and don't even notice it.  I usually have at least 15 Chrome windows open at once.

**Comment by cooperq** [comment] 2015-07-20 19:45
duplicate of #319

**Closed by cooperq** 2015-07-20 19:45 UTC
Labels: duplicate
