### ISSUE TITLE
Window title = "chrome-extension://pkehgij ... /firstRun.html" (in Ubuntu 14.04)

### ISSUE THREAD

**Issue by mx44** [EFForg/privacybadgerchrome#293] opened 2014-09-23 11:11 UTC
When the browser window is not maximized, the unified menu-bar receives the name/page of the plugin rather than the title of the  tab having focus. This happens consistently for every new window, not only "first run."

**Comment by SwartzCr** [comment] 2015-04-03 22:27
Huh, I've never experienced this issue. Is it still happening @mx44 ?
I run debian and never have full sized windows and have never noticed this. What version of chrome are you running?

**Comment by mx44** [comment] 2015-04-04 00:32
Yes, it is still like that.

Ubuntu is a bit like OS X, it displays the window-title of the focused
window at the top of the screen  which is then replaced by the menu bar of
the focused window when you reach for it. It is THAT window-title which is
buggy. You won't see it in Debian.

**Comment by cooperq** [comment] 2015-07-21 03:55
I am running ubuntu and have also never been able to reproduce  this. I don't think this is a privacy badger bug. Closing until I can find steps to reproduce.

**Comment by mx44** [comment] 2015-07-21 08:38
This is using 14.04 with the standard Unity interface (menubar at top
rather than for each window) and Google-chrome (not Chromium which is a
different product.)

**Comment by cooperq** [comment] 2015-07-24 00:41
I tried reproducing this with Chrome proper in ubuntu and was unable to reproduce it at all. I think this is probably a bug in chrome or ubuntu.

**Closed by cooperq** 2015-07-24 00:41 UTC
Labels: bug, ui
