### ISSUE TITLE
Privacy Badger blocks Github avatars

### ISSUE THREAD

**Issue by jleclanche** [EFForg/privacybadgerchrome#443] opened 2015-06-24 12:53 UTC
Avatars are now on `avatars{0..3}.githubusercontent.com`. PB blocks all that by default.

**Comment by cooperq** [comment] 2015-06-24 19:33
thats odd, privacy badger has githubusercontent.com on its cookie block list, so those shouldn't be blocked at all. Can you send me a screenshot of privacy badger's settings on a github page where the avatars are being blocked?

**Comment by jleclanche** [comment] 2015-06-24 20:43
These three were all set to block. I changed it to block cookies only. It's something that only started happening *today*.

![image](https://cloud.githubusercontent.com/assets/235410/8340979/4dd8f412-1ac2-11e5-9299-cf48f9da2f3f.png)

**Comment by jleclanche** [comment] 2015-06-24 20:44
In fact now that I added that image, I can see that `cloud.githubusercontent.com` is blocked as well. The image is blocked.

**Comment by SwartzCr** [comment] 2015-06-29 19:02
Hey jleclanche
If you don't mind can you go into your inspector and get some more information about the state of Privacy Badger?
Go to your extensions page chrome://extensions and get to the Background Page for Privacy Badger, (it should be linked under the Privacy Badger entry on that page, though you may need to enable developer mode)
Can you give me the output of FilterStorage.knownSubscriptions.frequencyHeuristic.filters
and similarly for FilterStorage.knownSubscriptions.userYellow.filters, and FilterStorage.knownSubscriptions.userRed.filters
this data might give information about your overall browsing, so feel free to remove listings from sites that don't seem relevant.
if that's too difficult I can write up a script to get this information out of the console

**Comment by jleclanche** [comment] 2015-06-29 19:06
@swartzcr hey! There's a lot of data in there, 36 filters for `FilterStorage.knownSubscriptions.frequencyHeuristic.filters` and 29 for `FilterStorage.knownSubscriptions.userYellow.filters`.

There's just one for `FilterStorage.knownSubscriptions.userRed.filters`: `||ssl.google-analytics.com^$third-party`.

**Comment by jleclanche** [comment] 2015-06-29 19:07
I see the various githubusercontent values in userYellow, but keeping in mind that I did change them since I filed this bug since I use github a lot.

**Comment by SwartzCr** [comment] 2015-06-29 19:16
try this: chrome.storage.local.get('cookieblocklist', function(x){console.log(x)});
and tell me what you see

**Comment by jleclanche** [comment] 2015-06-29 19:49
```
VM147:2 Object {cookieblocklist: Array[3]}cookieblocklist: Array[3]0: "google.com"1: "paypalobjects.com"2: "soundcloud.com"length: 3__proto__: Array[0]__proto__: Object
```

**Comment by SwartzCr** [comment] 2015-06-29 20:47
Great! I think I know what this bug is, it looks to be the same problem as #405, I should have a fix later this week.

**Comment by jleclanche** [comment] 2015-06-29 20:55
\o/

**Comment by cooperq** [comment] 2015-06-30 00:21
@jleclanche can you also tell us what the value of `FilterStorage.knownSubscriptions['https://www.eff.org/files/cookieblocklist.txt']` is? How many filters it has and what the value of `lastModified` is?

**Comment by jleclanche** [comment] 2015-06-30 00:32
```
_downloadStatus: "synchronize_connection_error"_errors: 1
_lastCheck: 1435622048
_lastDownload: 1470196130
_title: "EFF Auto Whitelist"
disabled: (...)
downloadStatus: (...)
errors: (...)
expires: 1401414434
filters: Array[330][0 … 99][100 … 199][200 … 299][300 … 329]  length: 330
fixedTitle: (...)
homepage: (...)
lastCheck: (...)
lastDownload: (...)
lastModified: "Wed, 07 May 2014 21:25:13 GMT"
lastSuccess: 1400204474
softExpiration: 1411930814
title: (...)url: "https://www.eff.org/files/cookieblocklist.txt"
__proto__: Object
```

**Comment by SwartzCr** [comment] 2015-06-30 18:38
PR up in #457

**Comment by cooperq** [comment] 2015-06-30 18:44
Hmm, I think I see the problem here, your _lastDownload time is in 2016, which is certainly a problem and would mean that the code would never check for a new cookieblocklist which explains why you haven't updated the cookieblocklist since some time in 2014! It's no suprise that github isn't on there since it is a more recent addition. The bug that Noah discovered is definitely a problem, and it may be contributing to the problems you are seeing, but I think this is the real culprit. 
I'm curious how exactly the _lastDownload timestamp got set to a date in 2016, perhaps you were playing around with weird dates on your laptop or something? At any rate, I think the fix for this might be to change the _lastDownload timestamp to something matching _lastCheck maybe, and see if privacy badger will then download the appropriate cookie block list.

**Comment by jleclanche** [comment] 2015-06-30 18:46
> I'm curious how exactly the _lastDownload timestamp got set to a date in 2016, perhaps you were playing around with weird dates on your laptop or something?

Could have been yeah, but not lately. Thanks.

**Comment by cooperq** [comment] 2015-07-01 00:16
Oh wow actually looking at this further, it seems like the connection actually failed last time you tried to download it, I wonder if that could be the cause of the weird date. I think this warrants further investigation. It's  possible that there was a download error and then privacy badger never checked again, which would of course be a huge problem.

**Comment by cooperq** [comment] 2015-07-09 19:16
Will be fixed in the next release.

**Closed by cooperq** 2015-07-09 19:16 UTC
Labels: bug, High priority

**Comment by jleclanche** [comment] 2015-07-09 19:17
Thanks!
