### ISSUE TITLE
Privacy badger breaks chrome

### ISSUE THREAD

**Issue by bitsmag** [EFForg/privacybadgerchrome#793] opened 2016-03-31 17:23 UTC
Hey,

I have no idea how to reproduce that bug but it happend to me three times in the last two day. I tried to open a website and the site didn't load. This little notification in the bottom left corner of the browser told me "Waiting for extension Privacy badger". I could not load any other websites in other tabs and even videostreams stopped. I was not able to open the privacy badger menu. I then killed chrome with the task manager (not sure if this was necessary) and some notification told me "Privacy Badger has crashed please click here to reload the extension".

I'm running:
Windows 10
Chrome: Version 49.0.2623.110
Privacy Badger: 2016.3.2

**Comment by frosforever** [comment] 2016-04-01 14:22
@bitsmag I had the same issue. Relaunching chrome to ensure the latest updates were installed and then disabling and reenabling privacy badger extension seemed to fix it for now.

OS X 10.10.5
Chrome: Version 49.0.2623.110 (64-bit)
Privacy Badger:  2016.3.2

**Comment by a8ksh4** [comment] 2016-04-08 14:35
I've been seeing this for a few days, too.  Sometimes chrome stops loading web sites and it shows the "Waiting for extension privacy badger" message at the bottom... I have to disable and re-enable privacy badger when this happens. 

OSX 10.11.4
Chrome 49.0.2623.110 (64-bit)
Privacy Badger 2016.3.2

**Comment by andru** [comment] 2016-04-11 15:46
Same issue, also resolved by disabling and immediately enabling.

OSX 10.10.5
Chrome 49.0.2623.87
Privacy Badger 2016.4.6

**Comment by vball525** [comment] 2016-04-15 20:44
Was asked on Twitter to file a bug and this is the exact scenario. Happened all week and just 10 mins ago. OSX 10.11.4 Chrome 49.0.2623.112 (64-bit) Privacy Badger 2016.4.13. Is there anything else I can provide to help diagnose?

**Comment by cooperq** [comment] 2016-04-15 21:44
I know that @vball525 is still having this issue, are the rest of you still having this issue with privacy badger 2016.4.13 ?

**Comment by a8ksh4** [comment] 2016-04-15 22:03
I just reinstalled it since there is a new version... will post back if I run into probs again.

**Comment by cooperq** [comment] 2016-04-19 01:50
This actually seems like a duplicate of #449 so I am going to ask that you all continue the thread over there.

**Closed** 2016-04-19 01:50 UTC
Labels: duplicate
