### ISSUE TITLE
No need to block images that don't set cookies

### ISSUE THREAD

**Issue by koehn** [EFForg/privacybadgerchrome#545] opened 2015-08-10 19:34 UTC
Many distributed social media sites (e.g., Diaspora pods) use image links to allow clients to requests e.g. profile photos directly from the server hosting the profile. These photos often do not contain any tracking information (e.g., cookies). Sample URI that PB reports as a problem: https://diaspora.koehn.com/posts/767865

These show up on PrivacyBadger (1.0.0, Firefox 39.0.3) as "Yellow", indicating that PB is removing tracking information from the images. But there isn't any tracking information on the images in the first place. I don't think PB should warn users about images that are not being used for tracking.

If you want to whitelist all Diaspora pods, you can find a list of them (non-complete) at http://podupti.me (the list changes frequently, though).

**Comment by SwartzCr** [comment] 2015-09-15 00:48
unfortunately things that get flagged as tracking we'll block any requests to them. If you think privacy badger is flagging third-parties as setting cookies when they're not then that's a bug, but we're not going to change the workflow of PB where it blocks all requests after a thing has been marked as a tracker.
@cooperq what do you think of the feasibility of yellowlisting all diaspora pods?

**Comment by cooperq** [comment] 2015-09-16 00:23
So I don't think it's reasonable to whitelist all diaspora pods especially since they change often and we can't vouch for each one of them. I also don't understand why a diaspora pod would get blocked if it just sending images and not setting cookies, that seems like it would be a bug if that is happnening. Can you take me through the steps to reproduce a diaspora pod getting blocked?

**Closed** 2016-05-17 07:03 UTC
