### ISSUE TITLE
PrivacyBadgerChrome disables submit action on www.netjets.com

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#475] opened 2015-07-17 21:35 UTC
On first visit (no cookies) to https://www.netjets.com/ clicking on "Netjets US" should result in a submit action and the loading of https://www.netjets.com/Home/

This does not happen, unless Privacy Badger is disabled.

Standard updated Chrome on Win 7 Home Premium x64. No other extensions.

**Comment by SwartzCr** [comment] 2015-07-31 21:29
I can't reproduce this :(
I'm going to close this for now, @cypherpunk please open it again if it persists with the new version of Privacy Badger (should be released next week, or you can load the unpacked version from github branch master or stable)

**Closed by SwartzCr** 2015-07-31 21:29 UTC
Labels: Site-bug
