### ISSUE TITLE
Warning: This extension is slowing down Google Chrome.

### ISSUE THREAD

**Issue by babartareen** [EFForg/privacybadgerchrome#529] opened 2015-08-07 00:29 UTC
Getting following warning in chrome (Version 44.0.2403.130 (64-bit)) running on OS X (10.10.4 (14E46)).

*Warning:
This extension is slowing down Google Chrome. You should disable it to restore Google Chrome's performance.*

![screenshot at aug 06 17-26-10](https://cloud.githubusercontent.com/assets/5945898/9126270/4bc4a15c-3c60-11e5-9b9c-28a55859b8e4.png)

**Comment by SwartzCr** [comment] 2015-08-07 01:16
closing as a duplicate of #527 and #437

**Closed by SwartzCr** 2015-08-07 01:16 UTC
