### ISSUE TITLE
Cookieblocklist changes are not being deployed

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerchrome#419] opened 2015-06-12 03:54 UTC
For instance, #412 is still [not live](https://www.eff.org/files/cookieblocklist.txt)!

**Comment by cooperq** [comment] 2015-06-12 19:17
I have pushed it as of now, but the real solution here is to automate this in some fashion.

**Comment by SwartzCr** [comment] 2015-07-01 23:03
this may be related to the date issue in #443 
We should take a look at the code that sets the _lastUpdate date

**Comment by SwartzCr** [comment] 2015-07-20 17:17
looks like this was addressed in #466 and #457

**Comment by cooperq** [comment] 2015-07-20 19:47
This is not a bug, it is an issue about automatically uploading cookieblocklist changes to the EFF server. Just needs some tooling written. Leaving it open but this isn't a launch blocker.

**Comment by cooperq** [comment] 2015-07-25 18:50
I added a pre-push hook to my repo to automatically upload cookie block list changes. @SwartzCr, you should do the same, I will share my script with you.

**Closed by cooperq** 2015-07-25 18:50 UTC
Labels: Task
