### ISSUE TITLE
Save option

### ISSUE THREAD

**Issue by i5on9i** [EFForg/privacybadgerchrome#706] opened 2015-12-09 01:46 UTC
Hi, I appreciate your work.

Here, I have a suggestion for your extension

How about saving the options.?
I am using PrivacyBadger to protect specific cookies at every sites, so I spend lots of time to select the cookies I want to block.
but what if I erase the extensions, should I do it again?
How about make a export option for settings?

Take care
Regards

**Comment by cooperq** [comment] 2015-12-16 00:51
Thank your for your excellent suggenstion. Since this is a duplicate of #146 I am going to close it, but please feel free to add comments there.

**Closed by cooperq** 2015-12-16 00:51 UTC
