### ISSUE TITLE
yellowlist player.ooyala.com

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerchrome#736] opened 2016-02-02 08:31 UTC
Eg: http://www.vox.com/2016/2/2/10892752/bernie-sanders-iowa-speech

**Comment by cooperq** [comment] 2016-02-06 00:52
This seems like a good candidate for #400

**Comment by cooperq** [comment] 2016-05-17 06:59
duplicate of #577

**Closed by cooperq** 2016-05-17 06:59 UTC
