### ISSUE TITLE
stops loads

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#319] opened 2015-01-18 19:16 UTC
Disabling because my Chrome pageloads are now glacial! Will monitor for "New Faster Final 1.0 Release!"

**Comment by MrAlexWeber** [comment] 2015-02-05 01:03
I'm having a similar issue. More specifically, when loading tabs in the background, the current (foreground) tab becomes unresponsive until the new tabs are finished loading.
Chrome 40, Mac OS X 10.10.1

**Comment by cooperq** [comment] 2015-02-09 19:50
hmm, I will have to look into this more. Are you running any other extensions that could be causing this issue?

**Comment by MrAlexWeber** [comment] 2015-02-09 19:58
I run a fair amount of other extensions, but my testing process suggests it was in fact PB causing the problem… I don't have any extensions enabled in Incognito.

1. open Incognito tab
2. open test page (spaceipsum.com)
3. test scrolling (result: smooth)
4. open many links to twitter pages in the background
5. immediately test scrolling (still smooth)
6. change settings and enable PB for Incognito tabs, repeat test (result: scrolling hangs/lags/chugs while loading other pages)

**Comment by cooperq** [comment] 2015-02-09 20:15
Interesting, I haven't done much testing in incognito mode, I will have to look into this more.

**Comment by mrljp** [comment] 2015-03-07 21:58
I've also experienced this problem and finally narrowed it down to Privacy Badger.

Specifically, I am seeing what @MrAlexWeber described. However, I didn't notice the problem so much until I pulled one of the tabs off and created a separate window (e.g., I have 2 Chrome windows). Both windows exhibit the problem.

The behavior I am seeing is:

1. Load a page in the foreground tab A. This can be a new page or click a link.
2. Switch to another tab B. This tab will be unresponsive as either:
 * nothing is rendered. The page is blank.
 * no response to interaction: scroll (with mouse or keyboard), clicking links
3. Tab B becomes responsive once tab A finishes loading.

Mac OS 10.10.2 (14C109)
Chrome Version 41.0.2272.76 (64-bit)

**Comment by cooperq** [comment] 2015-03-19 22:30
I am still unable to verify this bug, but I am curious if it is specific to the mac build of chrome sinc eyou both seem to be using a mac. I will test my theory and let you know.

**Comment by SwartzCr** [comment] 2015-04-21 00:38
are there specific sites that this problem happens on or is it across all domains?
Is there anything showing up in the error console? (either if you right click inspect element on the PB drop down or if you go to chrome://extensions and click inspect views: background page)

**Comment by MrAlexWeber** [comment] 2015-04-21 17:45
Noah, when I tested, it was consistent across ALL pages.

**Comment by SwartzCr** [comment] 2015-04-22 19:01
Yuck!
anything showing up in the error console?

**Comment by cooperq** [comment] 2015-05-27 17:14
@MrAlexWeber I am still unable to reproduce this behavior. Can you tell me what version of your browser, what OS, and what version of privacy badger you are running? Also could you try building a version of privacy badger from the latest master on github and see if that fixes the problem?

**Comment by SwartzCr** [comment] 2015-07-10 21:47
@MrAlexWeber I just tried this and got the same sort of stopped scrolling both with privacy Badger enabled and without. 
@mrljp you seem to imply that this is happening when a single new tab is opened, is that correct?
If you're both willing to try to load the new stable version of Privacy Badger and see if this still happens I would greatly appreciate it (https://github.com/EFForg/privacybadgerchrome/tree/stable) (to install an unpacked extension git clone the repository then "enable developer mode in chrome://extensions, hit the "load unpacked extension" button and load up this directory.")

**Comment by SwartzCr** [comment] 2015-07-10 23:23
I just pushed a branch with some simple profiling on all of the blocking requests: https://github.com/EFForg/privacybadgerchrome/tree/performance
when I ran some tests with (load twitter, open a bunch of profiles in new tabs, watch the browser grind to a halt) the times that the profiling reported being spent inside of these function calls seemed negligable. Meanwhile it seemed like a lot of time was being spent outside of them, the console logs would stop for large periods of time, and then flood the background page console, sites would remain blank for long periods with a note 'waiting for extension Privacy Badger' and so on.
This seems like it may be a problem with chromes IPC, or possibly even a deadlock situation between multiple threads hitting the blocking calls?
I would love for a better way to debug this

**Comment by zachfedor** [comment] 2016-03-23 18:13
I may be seeing this behavior too, or something similar at least. Occasionally on opening a new tab and using the omnibar for a search or site entry, the new tab refuses to load. If I go to another tab and try to reload it, that hangs too. It reminds me of a network interruption, but I'm not seeing it anywhere else. This happens for any site. If I open an incognito tab and try the same search or site, it comes up fine. I don't have PB enabled in incognito. If I go to the Extension page and disable PB, the page starts loading immediately. 

I'm on Chrome 49.0.2623.87 (64-bit) on OS X 10.11.3

**Comment by mrljp** [comment] 2016-03-24 14:48
I recently re-enabled PB and I am no longer seeing the original problem. I do see the behavior where pages, or parts of pages, don't render due to tracking sites being blocked. If I fiddle with the PB settings or disable PB for the site, the page works fine. An example URL where part of the page is blocked is at
https://confluence.atlassian.com/search/?query=admin%20more%3Apagemap%3Ametatags-ajs-space-key%3AJIRASOFTWARESERVER071
where the search results do not show. This is due to PB blocking cdn.rawgit.com.

For me, the original problem appears to be resolved.

PB 2016.3.2
Chrome 49.0.2623.87 (64-bit)
Mac OSX 10.11.3 (15D21)

**Comment by ibash** [comment] 2016-04-22 14:12
Also reporting that I just saw a bug where loads were blocked. Even opening a new tab wouldn't load. Next time this comes up I'll check the PB debugger.

PB  2016.4.13
Chrome 49.0.2623.112
OSX 10.11.4

**Comment by cooperq** [comment] 2016-04-22 17:38
I suspect that this is the same issue as #449, do you see the "waiting for privacy badger" text at the bottom when it stops loading?

**Comment by ibash** [comment] 2016-04-22 21:00
I'll keep an eye out

**Comment by ibash** [comment] 2016-05-13 18:00
Hi, just hit this again.

A screenshot:

![screen shot 2016-05-13 at 10 50 59 am](https://cloud.githubusercontent.com/assets/204566/15256952/de9ab118-18f8-11e6-9a60-ed4e7b9d42ec.png)

The inspector on the right int he privacy badger background page - as you can see there are no elements or javascript contexts.

On another project I am also working on a chrome extension and we've hit a similar case where the inspector will be rendered without elements / contexts. That happens when there's an infinite loop in the code and then you try to open the inspector.

Our  infinite loop happens infrequently enough that it's hard to track down, so we made an [infinite loop detection tool](https://github.com/ibash/loop-detection) that transforms javascript and adds in a guard to all loops (take a look at [this test file](https://github.com/ibash/loop-detection/blob/master/test/transformer_test.js) to see what I mean).

If you're interested in using the tool let me know and I can help integrate it, we added it to our build process with a [webpack loader](https://github.com/ibash/loop-detection-loader), I imagine you can do the same with grunt.

**Comment by cooperq** [comment] 2016-05-17 05:48
Okay, This should be completely fixed in the latest version of privacy badger. As of today I have only deployed it to 10% of users (it has some huge changes!) but if you want to try it out early you can take the following steps. 
1. Download the crx file [from the chrome web store] (https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP1rX98iOE5SwxVXgdVTMTKqobiCFyOuS_jNFoVMdRhW-bEA7QhvVJw2hrKrZS8b8ThMYsv0t-wxxLr4D-Sm2ZC1AMZSmuW2zjq5MsW529CVI2Rtq2QO7xWEQg/pkehgijcmpdhfbdbbnkijodmdjhbjlgp_main.crx)
2. Open a new tab to [chrome://extensions](chrome://extensions)
3. Drag the downloaded file and drop it onto the extensions window. 
You should now have Privacy Badger version 2016.5.15
If this doesn't fix the problem please let me know. If you find any new bugs please file a separate issue.

**Comment by ibash** [comment] 2016-05-17 16:20
Installed -- I'll keep an eye out

**Closed** 2016-05-25 01:06 UTC
Labels: bug
